//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinova.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedinovaDbEntities1 : DbContext
    {
        public MedinovaDbEntities1()
            : base("name=MedinovaDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutItems> AboutItems { get; set; }
        public virtual DbSet<Abouts> Abouts { get; set; }
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Banners> Banners { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<AppointmentSettings> AppointmentSettings { get; set; }
    }
}
